<a href="https://colab.research.google.com/github/Yesenia-AriasC/Introduccion-a-Numpy/blob/main/1_Arrays_y_tipos_de_dato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Picture title](image-20221227-212312.png)

# ¿Por qué NumPy?
Es una librería enfocada al cálculo númerico y manejo de Arrays.
1. Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
2. Optimiza el almacenamiento en memoria.
3. Además, maneja distintos tipos de datos.

Es una librería muy poderosa, se pueden crear redes neuronales desde cero.

## Importar Numpy

In [ ]:
import numpy as np

# Numpy array

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

* Es la estructura central de Numpy
* Representa los datos de una manera estructurada
* Indexado (puedo identificar )
* Acceso a uno o más elementos

In [ ]:
# Creo una lista

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Convierto a array

arr = np.array(lista) # Este objeto tiene una sola dimensión
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape


(9,)

## Creando array de múltiple dimensión

Crearemos un array de 2 dimensiónes, pues ahora necesito 2 números para ubicar un elemento dentro de mi array.

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [ ]:
matriz.shape

(4, 3)

In [ ]:
matriz.size

12

## Acceder a elementos del Array

In [ ]:
print(arr[0], arr[2], "La suma de lo anterior es:" ,arr[0]+arr[2], sep="\n")

1
3
La suma de lo anterior es:
4


In [ ]:
print(matriz[0], matriz[0,0], sep="\n")

[1 2 3]
1


### Slicing

Recuerde que python comienza a contar desde 0

In [ ]:
print(arr)
print(arr[1:3]) # imprime las posiciones 1 y 2 (no imprime la tercera)
print(arr[:3])  # desde el inicio hasta la posiión 2
print(arr[3:])  # posicion 3 en adelante
print(arr[:])   # Todo
print(arr[::3]) # Todos pero de 3 en 3 -> posiciones 0, 3 y 6
print(arr[-1])  # Primer valor desde el final hasta el comienzo
print(arr[::-1])# Toda la lista pero en orden "al revés"
print(arr[-3:]) # Los 3 últimos valores

[1 2 3 4 5 6 7 8 9]
[2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7]
9
[9 8 7 6 5 4 3 2 1]
[7 8 9]


In [ ]:
print(matriz, end="\n\n")
print(matriz[1:], end="\n\n") # Fila 1 en adelante
print(matriz[1:,0:2])         # Fila 1 en adelante y primeras dos columnas

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]

[[4 5 6]
 [7 8 9]
 [7 8 9]]

[[4 5]
 [7 8]
 [7 8]]


# Tipos de dato Numpy
[Todos los tipos de dato aquí](https://numpy.org/doc/stable/user/basics.types.html)

Los arrays de NumPy solo pueden contener __un tipo de dato__, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

El array de Numpy únicamente puede tener un único tipo de datos en el cual va a trabajar. No puedo tener la mitad del array en int y la otra mitad en bool.

Podemos conocer el tipo de datos del array consultando la propiedad ```.dtype```

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

## dtype

Si queremos usar otro tipo de dato, lo podemos definir en la declaración del array.

In [ ]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
print(arr.dtype)
print(arr) # Ya tienen punto decimal

float64
[1. 2. 3. 4.]


## .astype()

Si ya se tiene el array definido, se utiliza el método ```.astype()``` para convertir el tipo de dato.

### .astype(np.float64)

Tipo flotante - Trabaja mejor con las redes neuronales / Tensorflow y Pytorch.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

### .astype(np.bool_)

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

### .astype(np.string_)

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

### .astype(np.int8)

De igual manera, se puede pasar de string a número.

__(Si un elemento no es de tipo número, el método falla.)__

In [ ]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [ ]:
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c8549269-a2eb-416d-b4b6-9a86d3809a7d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>