<a href="https://colab.research.google.com/github/Yesenia-AriasC/Introduccion-a-Numpy/blob/main/3_Creando_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Numpy ofrece diferentes formas para crear un array,  para ver todas, hacer clic [aquí](https://numpy.org/doc/stable/reference/routines.array-creation.html).
Algunas de estas son:

# Crear array sin definir una lista previamente

## .arange()

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Un tercer argumento dice el "salto" 

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Definir estructuras o esquemas
ver todas las formas [aquí](https://numpy.org/doc/stable/reference/routines.array-creation.html#from-shape-or-value)

## .zeros()

In [ ]:
np.zeros(3)


array([0., 0., 0.])

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#help(np.zeros)

## .ones()

In [ ]:
np.ones(3)

array([1., 1., 1.])

# Rangos numéricos | .linspace()

para ver todas las formas de crear arrays numéricos, clic [aquí](https://numpy.org/doc/stable/reference/routines.array-creation.html#numerical-ranges).

```np.linspace()``` Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

In [ ]:
np.linspace(0,10,10) # Inicia en 0, termina en 10 y tiene 10 divisiones

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# matriz diagonal | .eye()

https://numpy.org/doc/stable/reference/routines.array-creation.html#from-shape-or-value

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Generar aleatorios


[numpy.random](https://numpy.org/doc/1.16/reference/routines.random.html)

* __rand(d0, d1, …, dn)__	Random values in a given shape.

* __randn(d0, d1, …, dn)__	Return a sample (or samples) from the “standard normal” distribution.

* __randint(low[, high, size, dtype])__	Return random integers from low (inclusive) to high (exclusive).

* __random_integers(low[, high, size])__	Random integers of type np.int between low and high, inclusive.

* __random_sample([size])__	Return random floats in the half-open interval [0.0, 1.0).

* __random([size])__	Return random floats in the half-open interval [0.0, 1.0).

* __ranf([size])__	Return random floats in the half-open interval [0.0, 1.0).

* __sample([size])__	Return random floats in the half-open interval [0.0, 1.0).

* __choice(a[, size, replace, p])__	Generates a random sample from a given 1-D array
bytes(length)	Return random bytes.

## .rand()

In [ ]:
np.random.rand()

0.583853914627645

In [ ]:
np.random.rand(4)

array([0.07824048, 0.67194714, 0.99452882, 0.65091395])

In [ ]:
np.random.rand(4,4)

array([[0.58742795, 0.45801097, 0.64438875, 0.84997927],
       [0.78748387, 0.27100207, 0.48035921, 0.50784157],
       [0.64494721, 0.15508981, 0.53442992, 0.56887089],
       [0.23677076, 0.86276861, 0.56618108, 0.99402121]])

## .randint()
Generar números enteros

In [ ]:
# generar enteros del 1 al 14
np.random.randint(1, 15)

12

In [ ]:
np.random.randint(1, 15, (3,2))

array([[13,  1],
       [ 4, 13],
       [ 4,  7]])

## Bajo una distribución de probabilidad


[numpy.random](https://numpy.org/doc/1.16/reference/routines.random.html)


In [ ]:
np.random.binomial(3,0.5)

2

In [ ]:
from numpy.random import binomial
binomial(3,0.5)

3

Para ver más sobre esto, revisar [aquí](https://github.com/Yesenia-AriasC/Probabilidad/blob/c666ac22a1575c39cbe425cdb07aaf2821fd004f/Probabilidad_distrosDiscretas_Básicos.ipynb).