<a href="https://colab.research.google.com/github/Yesenia-AriasC/Introduccion-a-Numpy/blob/main/6_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Copy

Ver en la documentación [aquí](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

```.copy()``` nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

## Ejemplo

In [3]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Tomamos un trozo del arreglo
trozo_de_arr = arr[0:6]

Queremos pasar todas nuestras variables a 0

In [5]:
trozo_de_arr[:] = 0
trozo_de_arr 

array([0, 0, 0, 0, 0, 0])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

### Creando copia

Creemos una copia para no dañar el array original

In [7]:
arr_copy = arr.copy()
arr_copy[:] = 100

In [8]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])