<a href="https://colab.research.google.com/github/Yesenia-AriasC/Introduccion-a-Numpy/blob/main/7_Condiciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Condiciones

Permiten hacer consultas más específicas.

In [3]:
# Creamos un arreglo que inicie el 1 y termine en 10, con 10 divisiones

arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

## Array Booleano ¿cumplen la condición?

Señala qué posiciones cumplen con la condición.

In [4]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

## Array de los valores que cumplen la condición
Regresa los valores para dónde la condiciones True.

(Es una esoecie de slice pero que tiene en cuenta la condición)

In [5]:
arr[indices_cond] 

array([ 6,  7,  8,  9, 10], dtype=int8)

## Modificar los valores que cumplan la condición

In [7]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

# Múltiples condiciones

## Conjunción | &

(Es una esoecie de slice pero que tiene en cuenta la condición conjunta)

In [6]:
arr[(arr > 5) & (arr < 9)] 

array([6, 7, 8], dtype=int8)

## np.where(condicion, valor si cumple, valor si no cumple)

In [9]:
matriz = np.array([[19,  4, 43],
       [ 8, 96, 80],
       [ 6, 99, 35]])

In [10]:
np.where(matriz > 50, 0, 1)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])