<a href="https://colab.research.google.com/github/Yesenia-AriasC/Introduccion-a-Numpy/blob/main/8_Operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Operaciones
[Working with mathematical formulas](https://numpy.org/doc/stable/user/absolute_beginners.html#working-with-mathematical-formulas)

Definamos los arreglos con los que trabajaremos

In [2]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Multipicar por un escalar

In [3]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
matriz*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Suma 

## Suma de un escalar

### Vector

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Matriz

In [11]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
matriz+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

## Suma de arrays / matrices

Sumar dos arrays de igual dimensiones las hace elemento por elemento:

In [22]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Aplica también para matrices

In [21]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Dividir un escalar por un vector / matriz

### Vector

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
1/arr

<ipython-input-13-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### Matriz

In [15]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
1/matriz

<ipython-input-16-5153dd94ba41>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/matriz


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

# Exponencial

### Vector

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Matriz

In [19]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz**2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

# Multiplicación de matrices

In [23]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## .matmul()

In [26]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

## @

In [27]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])